import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
import { AppRouter } from "../../router"
import { ParkDesk } from "./ParkDesk"
const fetchMock=vi.fn();vi.stubGlobal("fetch",fetchMock);const ok=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s});const d={id:"p",original_text:"raw",status:"sealed",released:false,releases:[],forged_into:[]};afterEach(cleanup);beforeEach(()=>fetchMock.mockReset());function view(){return render(<AppRouter><ParkDesk captureId="p"/></AppRouter>)}
async function open(){fetchMock.mockResolvedValue(ok(d));view();fireEvent.click(await screen.findByRole("button",{name:"主动放行"}))}
describe("PARK release command guards",()=>{
 it("new workspace sends exact body",async()=>{await open();fireEvent.change(screen.getByLabelText("新的开放问题"),{target:{value:"open?"}});fetchMock.mockResolvedValueOnce(ok({workspace_id:"w"}));fireEvent.click(screen.getByRole("button",{name:"确认放行"}));await waitFor(()=>expect(fetchMock.mock.calls.some(([u])=>String(u).includes("/release"))).toBe(true));const x=JSON.parse(fetchMock.mock.calls.find(([u])=>String(u).includes("/release"))![1].body);expect(x).toMatchObject({provisional_role:"unnamed",question:"open?",workspace_expected_sequence:0});expect(x.workspace_id).toBeUndefined();expect(x.command_id).toBeTruthy()})
 it("existing workspace sends exact body",async()=>{fetchMock.mockImplementation((url:unknown)=>{const p=String(url);if(p.endsWith("/park-captures/p"))return Promise.resolve(ok(d));if(p.endsWith("/universes/active"))return Promise.resolve(ok({id:"u"}));if(p.includes("/universes/u/home"))return Promise.resolve(ok({workspaces:[{id:"w",question:{text:"Q"}}],pending_facts:[]}));if(p.includes("/release"))return Promise.resolve(ok({workspace_id:"w"}));return Promise.resolve(ok([]))});view();fireEvent.click(await screen.findByRole("button",{name:"主动放行"}));fireEvent.click(screen.getAllByLabelText("已有工作区")[0]);fireEvent.change(screen.getByRole("combobox",{name:"已有工作区"}),{target:{value:"w"}});fireEvent.click(screen.getByRole("button",{name:"确认放行"}));await waitFor(()=>expect(fetchMock.mock.calls.some(([u])=>String(u).includes("/release"))).toBe(true));const x=JSON.parse(fetchMock.mock.calls.find(([u])=>String(u).includes("/release"))![1].body);expect(x).toMatchObject({provisional_role:"unnamed",workspace_id:"w",workspace_expected_sequence:0});expect(x.question).toBeUndefined()})
 it("retry retains release envelope and double click posts once",async()=>{await open();fireEvent.change(screen.getByLabelText("新的开放问题"),{target:{value:"open?"}});fetchMock.mockResolvedValueOnce(ok({detail:"net"},503)).mockResolvedValueOnce(ok({workspace_id:"w"}));const b=screen.getByRole("button",{name:"确认放行"});fireEvent.click(b);fireEvent.click(b);await screen.findByRole("alert");fireEvent.click(screen.getByRole("button",{name:"确认放行"}));await waitFor(()=>expect(fetchMock.mock.calls.filter(([u])=>String(u).includes("/release"))).toHaveLength(2));const c=fetchMock.mock.calls.filter(([u])=>String(u).includes("/release"));expect(c[0][1].body).toBe(c[1][1].body)})
})
