import { useEffect, useRef, useState, type FormEvent } from "react"
import { command, researchUniverse } from "../api"
import type { CommandEnvelope, ParkReleaseRef } from "../types"
import { useNavigation } from "../../../router"

type ForgeIntent = { claim: CommandEnvelope & { text: string }; claimId?: string; provenance?: CommandEnvelope & { claim_id: string; capture_id: string; release_id: string }; review?: CommandEnvelope }
export function ReleaseForge({ workspaceId, releaseRef }: { workspaceId: string; releaseRef: ParkReleaseRef }) {
  const { navigate } = useNavigation(); const [claim, setClaim] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string>(); const intent = useRef<ForgeIntent | undefined>(undefined); const flight = useRef<Promise<void> | undefined>(undefined); const route = useRef(0)
  useEffect(() => { route.current++; intent.current = undefined; flight.current = undefined; setPending(false); setError(undefined); setClaim("") }, [workspaceId, releaseRef.id])
  function submit(e: FormEvent) { e.preventDefault(); if (!claim.trim() || pending || flight.current) return; const generation = route.current; intent.current ??= { claim: command({ text: claim.trim() }, 0) }; setPending(true); flight.current = (async () => { try { if (!intent.current!.claimId) intent.current!.claimId = (await researchUniverse.createClaim(workspaceId, intent.current!.claim)).result.claim_id; if (generation !== route.current) return; intent.current!.provenance ??= command({ claim_id: intent.current!.claimId!, capture_id: releaseRef.capture_id, release_id: releaseRef.id }, 0); await researchUniverse.forgeProvenance(workspaceId, intent.current!.provenance); if (generation !== route.current) return; intent.current!.review ??= command({}, 0); const review = await researchUniverse.startReview(intent.current!.claimId!, intent.current!.review); if (generation !== route.current) return; intent.current = undefined; navigate(`/review-rounds/${review.result.review_round_id}`) } catch (x) { if (generation !== route.current) return; setError(intent.current?.claimId ? "主张已保存，但谱系或挑战尚未形成。可以重试。" : x instanceof Error ? x.message : "提交失败") } finally { if (generation === route.current) { flight.current = undefined; setPending(false) } } })() }
  return <section className="ru-focus-surface" aria-labelledby="forge-title"><p className="ru-kicker">锻 · 自写 claim</p><h2 id="forge-title">把自己的判断写出来。</h2><p>你在断言什么？适用范围是什么？什么会构成反例？</p><p>这份 PARK 原件只作为谱系引用；不会把它的文字带入 claim。</p>{error && <p className="ru-error" role="alert">{error}</p>}<form className="ru-claim-form" onSubmit={submit}><label htmlFor="forged-claim">由你亲自写下的 claim</label><textarea id="forged-claim" value={claim} disabled={pending} onChange={e => { setClaim(e.target.value); if (!pending) intent.current = undefined }} placeholder="从空白处写下你的主张。" required /><button className="ru-ink-button" disabled={pending}>{pending ? "正在提交…" : "提交检验"}</button></form><button className="ru-quiet-button" onClick={() => navigate(`/workspaces/${workspaceId}?source-release=${encodeURIComponent(releaseRef.id)}`)}>跳过锻，直接提交已成形自写 Claim</button></section>
}
