import { useEffect, useRef, useState, type FormEvent } from "react"
import { command, researchUniverse } from "../api"
import type { CommandEnvelope, MaterialPurpose, ParkReleaseRef, WorkspaceDesk as Desk } from "../types"
import { ReleaseForge } from "./ReleaseForge"
import { useNavigation } from "../../../router"

type Selection = { start: number; end: number; selected_text: string }
type ClaimIntent = { claim: CommandEnvelope & { text: string }; claimId?: string; provenance?: CommandEnvelope & { claim_id: string; capture_id: string; release_id: string }; review?: CommandEnvelope }
export function WorkspaceDesk({ workspaceId, forgeReleaseRefId, sourceReleaseId }: { workspaceId: string; forgeReleaseRefId?: string; sourceReleaseId?: string }) {
  const { navigate } = useNavigation(); const [desk, setDesk] = useState<Desk | null>(null); const [sourceRef, setSourceRef] = useState<ParkReleaseRef | undefined>(); const [note, setNote] = useState(""); const [selected, setSelected] = useState<Selection>(); const [claim, setClaim] = useState(""); const [error, setError] = useState<string>(); const [conflict, setConflict] = useState(false); const [savePending, setSavePending] = useState(false); const draftGeneration = useRef(0); const noteCommand = useRef<(CommandEnvelope & { text: string }) | undefined>(undefined); const anchorCommand = useRef<(CommandEnvelope & { note_id: string; note_revision_id: string; start: number; end: number; selected_text: string }) | undefined>(undefined); const claimIntent = useRef<ClaimIntent | undefined>(undefined); const claimFlight = useRef<Promise<void> | undefined>(undefined); const routeGeneration = useRef(0); const routeId = useRef(workspaceId); const [claimPending, setClaimPending] = useState(false); const [claimStage, setClaimStage] = useState<"idle" | "saving-claim" | "generating-challenge" | "review-error">("idle"); const [materialExcerpt, setMaterialExcerpt] = useState(""); const [materialSource, setMaterialSource] = useState(""); const [materialPurpose, setMaterialPurpose] = useState<MaterialPurpose>("evidence"); const [materialUnparsable, setMaterialUnparsable] = useState(false); const [materialPending, setMaterialPending] = useState(false); const materialCommand = useRef<(CommandEnvelope & { excerpt: string; source_locator?: string | null; parse_status: "parsed" | "failed"; purpose: MaterialPurpose }) | undefined>(undefined);
  async function load(accept = () => true) { try { const value = await researchUniverse.desk(workspaceId); if (accept()) { setDesk(value); if (!noteCommand.current && draftGeneration.current === 0) setNote(value.note?.text ?? ""); setError(undefined) } } catch (e) { if (accept()) setError(e instanceof Error ? e.message : "读取失败") } }
  useEffect(() => { let live = true; routeGeneration.current++; routeId.current = workspaceId; noteCommand.current = undefined; anchorCommand.current = undefined; claimIntent.current = undefined; claimFlight.current = undefined; materialCommand.current = undefined; setSavePending(false); setClaimPending(false); setMaterialPending(false); setMaterialExcerpt(""); setMaterialSource(""); setMaterialPurpose("evidence"); setMaterialUnparsable(false); setSourceRef(undefined); setClaimStage("idle"); setConflict(false); setDesk(null); setError(undefined); setSelected(undefined); draftGeneration.current = 0; void load(() => live); return () => { live = false } }, [workspaceId])
  function editNote(text: string) { draftGeneration.current++; setNote(text); setSelected(undefined); noteCommand.current = undefined }
  const isCurrent = (generation: number, id: string) => generation === routeGeneration.current && id === routeId.current
  async function saveNote() { if (!desk || savePending) return; const currentGeneration = routeGeneration.current, currentId = workspaceId; const generation = draftGeneration.current; noteCommand.current ??= command({ text: note }, desk.sequence); setSavePending(true); try { const result = await researchUniverse.saveNote(currentId, noteCommand.current); if (!isCurrent(currentGeneration, currentId)) return; noteCommand.current = undefined; const fragment = result.fragment as Desk | undefined; if (fragment?.id) { setDesk(fragment); if (draftGeneration.current === generation) { setNote(fragment.note?.text ?? note); draftGeneration.current = 0 } void load(() => isCurrent(currentGeneration, currentId)) } else void load(() => isCurrent(currentGeneration, currentId)) } catch (e) { if (!isCurrent(currentGeneration, currentId)) return; setError(e instanceof Error ? e.message : "保存失败"); if ((e as { status?: number }).status === 409) { noteCommand.current = undefined; setConflict(true); void load(() => isCurrent(currentGeneration, currentId)) } } finally { if (isCurrent(currentGeneration, currentId)) setSavePending(false) } }
  async function anchor() { if (!desk?.note || !selected || note !== desk.note.text || savePending) return; const currentGeneration = routeGeneration.current, currentId = workspaceId; anchorCommand.current ??= command({ note_id: desk.note.note_id ?? desk.note.id, note_revision_id: desk.note.revision_id, ...selected }, desk.sequence); try { await researchUniverse.createAnchor(currentId, anchorCommand.current); if (!isCurrent(currentGeneration, currentId)) return; anchorCommand.current = undefined; void load(() => isCurrent(currentGeneration, currentId)) } catch (e) { if (!isCurrent(currentGeneration, currentId)) return; setError(e instanceof Error ? e.message : "锚点失败"); if ((e as { status?: number }).status === 409) { anchorCommand.current = undefined; setConflict(true); void load(() => isCurrent(currentGeneration, currentId)) } } }
  function forge(e: FormEvent) { e.preventDefault(); if (!desk || !claim.trim() || claimFlight.current) return; const currentGeneration = routeGeneration.current, currentId = workspaceId; claimIntent.current ??= { claim: command({ text: claim.trim() }, 0) }; setClaimPending(true); setClaimStage(claimIntent.current.claimId ? "generating-challenge" : "saving-claim"); claimFlight.current = (async () => { try { if (!claimIntent.current!.claimId) { const made = await researchUniverse.createClaim(currentId, claimIntent.current!.claim); if (!isCurrent(currentGeneration, currentId)) return; claimIntent.current!.claimId = made.result.claim_id; if (sourceRef && !claimIntent.current!.provenance) claimIntent.current!.provenance = command({ claim_id: made.result.claim_id, capture_id: sourceRef.capture_id, release_id: sourceRef.id }, 0) } if (claimIntent.current!.provenance) { await researchUniverse.forgeProvenance(currentId, claimIntent.current!.provenance); if (!isCurrent(currentGeneration, currentId)) return } if (!claimIntent.current!.review) { claimIntent.current!.review = command({}, 0); setClaimStage("generating-challenge") } const review = await researchUniverse.startReview(claimIntent.current!.claimId!, claimIntent.current!.review!); if (!isCurrent(currentGeneration, currentId)) return; claimIntent.current = undefined; navigate(`/review-rounds/${review.result.review_round_id}`) } catch (x) { if (!isCurrent(currentGeneration, currentId)) return; setError(claimIntent.current?.claimId ? "主张已保存，但挑战尚未形成。可以重试，不会重复创建主张。" : (x instanceof Error ? x.message : "提交失败")); setClaimStage(claimIntent.current?.claimId ? "review-error" : "idle"); if ((x as { status?: number }).status === 409) { claimIntent.current = undefined; setConflict(true); void load(() => isCurrent(currentGeneration, currentId)) } } finally { if (isCurrent(currentGeneration, currentId)) { claimFlight.current = undefined; setClaimPending(false) } } })() }
  function reapply() { if (!desk) return; setConflict(false); noteCommand.current = undefined; anchorCommand.current = undefined; claimIntent.current = undefined; materialCommand.current = undefined; setError(undefined) }
  async function addMaterial() {
    if (!desk || materialPending || !materialExcerpt.trim()) return
    const currentGeneration = routeGeneration.current, currentId = workspaceId
    materialCommand.current ??= command({ excerpt: materialExcerpt.trim(), source_locator: materialSource.trim() || null, parse_status: materialUnparsable ? "failed" : "parsed", purpose: materialPurpose }, 0)
    setMaterialPending(true)
    try {
      await researchUniverse.addMaterial(currentId, materialCommand.current)
      if (!isCurrent(currentGeneration, currentId)) return
      materialCommand.current = undefined
      setMaterialExcerpt(""); setMaterialSource(""); setMaterialPurpose("evidence"); setMaterialUnparsable(false)
      void load(() => isCurrent(currentGeneration, currentId))
    } catch (e) {
      if (!isCurrent(currentGeneration, currentId)) return
      setError(e instanceof Error ? e.message : "带入材料失败")
      if ((e as { status?: number }).status === 409) { materialCommand.current = undefined; setConflict(true); void load(() => isCurrent(currentGeneration, currentId)) }
    } finally { if (isCurrent(currentGeneration, currentId)) setMaterialPending(false) }
  }
  useEffect(() => { const hinted = sourceReleaseId && desk ? (desk.park_release_refs ?? []).find(item => item.id === sourceReleaseId) : undefined; setSourceRef(current => current?.id === hinted?.id ? current : hinted) }, [desk, sourceReleaseId, workspaceId])
  if (!desk) return <section className="ru-state" role={error ? "alert" : undefined}>{error ?? "正在展开问题工作区…"}{error && <button className="ru-ink-button" onClick={() => void load()}>重试</button>}</section>
  const pending = desk.pending_challenges[0], anchorReady = Boolean(selected && desk.note && note === desk.note.text && !savePending), releaseRefs = desk.park_release_refs ?? [], pendingStatusLabel = pending?.status === "answered" ? "已回应 · 待裁决" : "待回应 challenge"
  const forgeRef = forgeReleaseRefId ? releaseRefs.find(item => item.id === forgeReleaseRefId) : undefined
  if (forgeReleaseRefId && !forgeRef) return <section className="ru-state" role="alert">未找到这份放行引用。<button className="ru-ink-button" onClick={() => navigate(`/workspaces/${workspaceId}`)}>回到工作区</button></section>
  const forging = Boolean(forgeRef)
  const workspaceSurface = <section className="ru-workspace"><header className="ru-question-spine"><p className="ru-kicker">问题工作区 · 探索中</p><h1>{desk.question.text}</h1>{releaseRefs.map(ref => <p key={ref.id} className="ru-provenance">来自密封 PARK 原件的放行引用 · {ref.provisional_role}{!forging && <> · <a href={`/workspaces/${workspaceId}/forge/${ref.id}`}>从此原件锻造自写 claim</a><button className="ru-quiet-button" onClick={() => setSourceRef(sourceRef?.id === ref.id ? undefined : ref)}>{sourceRef?.id === ref.id ? "不作为本次 claim 来源" : "作为本次 claim 来源"}</button></>}</p>)}</header>{error && <p className="ru-error" role="alert">{error}</p>}{conflict && <button className="ru-quiet-button" onClick={reapply}>按最新版本重新应用</button>}<div className="ru-desk-grid"><div className="ru-exploration"><div className="ru-surface-heading"><span>探索稿</span><small>自由记录观察、猜测和未成形判断。Cui 不会在这里回复，也不会自动把内容升格为 Claim 或证据。</small><button className="ru-quiet-button" disabled={savePending} onClick={() => void saveNote()}>保存当前版本</button></div><textarea aria-label="探索稿" className="ru-note" value={note} onChange={(e) => editNote(e.target.value)} onSelect={(e) => { const t = e.currentTarget; const selected_text = t.value.slice(t.selectionStart, t.selectionEnd); setSelected(note === desk.note?.text && selected_text ? { start: t.selectionStart, end: t.selectionEnd, selected_text } : undefined) }} placeholder="写下观察、猜测、反例或尚未成形的判断。" /><button className="ru-quiet-button" disabled={!anchorReady} onClick={() => void anchor()}>保留所选片段</button>{!forging && <form className="ru-claim-form" onSubmit={forge}><label htmlFor="claim">形成一个由你亲自写下的 claim</label><textarea id="claim" value={claim} disabled={claimPending || Boolean(claimIntent.current?.claimId)} onChange={(e) => { setClaim(e.target.value); if (!claimPending) claimIntent.current = undefined }} placeholder="你究竟在断言什么？" required />{claimStage !== "idle" && <p className="ru-claim-progress" aria-live="polite">{claimStage === "saving-claim" ? "正在保存主张…" : claimStage === "generating-challenge" ? "主张已保存，Cui 正在形成挑战…" : "主张已保存，挑战尚未形成。"}</p>}<button className="ru-ink-button" disabled={claimPending}>{claimStage === "review-error" ? "重新形成挑战" : claimStage === "saving-claim" ? "正在保存主张…" : claimStage === "generating-challenge" ? "Cui 正在形成挑战…" : "确认提交检验"}</button></form>}</div><aside className="ru-research-edge"><p className="ru-kicker">研究边缘</p>{pending ? <a className="ru-pending-fact" href={`/review-rounds/${pending.review_round_id}`}><span>{pendingStatusLabel}</span><strong>{pending.attack_surface}</strong></a> : <p className="ru-edge-empty">尚无待回应事实。</p>}</aside></div>
  <section className="ru-material-entry" aria-labelledby="material-entry-title"><p className="ru-kicker">带入材料</p><h2 id="material-entry-title">把一份材料带进这个问题</h2><p className="ru-challenge-note">材料先中立进入，保存不可变摘录；进入时它不声明支持或反对任何 claim。</p><form className="ru-material-form" onSubmit={(e) => { e.preventDefault(); void addMaterial() }}><label htmlFor="material-source">来源（可选）</label><input id="material-source" value={materialSource} onChange={(e) => setMaterialSource(e.target.value)} placeholder="标题 / 链接 / 作者……" /><label htmlFor="material-excerpt">摘录或观察</label><textarea id="material-excerpt" value={materialExcerpt} onChange={(e) => setMaterialExcerpt(e.target.value)} placeholder="写下不可变摘录；保存后不可改写。" required /><fieldset className="ru-material-purpose"><legend>它进入这个问题，暂时是：</legend><label><input type="radio" name="material-purpose" checked={materialPurpose === "evidence"} onChange={() => setMaterialPurpose("evidence")} /> 待取证材料</label><label><input type="radio" name="material-purpose" checked={materialPurpose === "reference"} onChange={() => setMaterialPurpose("reference")} /> 只作探索参考</label></fieldset><label className="ru-material-unparsable"><input type="checkbox" checked={materialUnparsable} onChange={(e) => setMaterialUnparsable(e.target.checked)} /> 这段摘录我无法判断</label><button className="ru-ink-button ru-active" disabled={materialPending || !materialExcerpt.trim()}>{materialPending ? "正在带入…" : "带入材料"}</button></form>{(desk.materials?.length ?? 0) > 0 && <div className="ru-materials-list"><p className="ru-kicker">已带入材料</p>{desk.materials!.map((m) => <article key={m.id} className="ru-material-card"><p className="ru-reading-copy">{m.excerpt}</p><p className="ru-provenance">{m.source_locator ?? "无来源定位"} · {m.purpose === "evidence" ? "待取证材料" : "只作探索参考"} · {m.parse_status === "failed" ? "无法判断" : "已解析"}</p></article>)}</div>}</section></section>
  return forging ? <div className="ru-forge-layout"><ReleaseForge workspaceId={workspaceId} releaseRef={forgeRef!} />{workspaceSurface}</div> : workspaceSurface
}
