import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
import { AppRouter } from "../../../router"
import { WorkspaceDesk } from "./WorkspaceDesk"
const fetchMock=vi.fn();vi.stubGlobal("fetch",fetchMock);const r=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s});const desk=(id:string,refs:any[]=[])=>({id,question:{text:id},sequence:1,note:null,note_revisions:[],anchors:[],claims:[],review_rounds:[],pending_challenges:[],park_release_refs:refs});const ref={id:"r",capture_id:"cap",provisional_role:"exploration"};afterEach(cleanup);beforeEach(()=>fetchMock.mockReset());function v(id="a",hint?:string){return render(<AppRouter><WorkspaceDesk workspaceId={id} sourceReleaseId={hint}/></AppRouter>)}
describe("authoritative provenance regressions",()=>{
 it("uses returned claim id in exact provenance body before review",async()=>{fetchMock.mockResolvedValueOnce(r(desk("a",[ref]))).mockResolvedValueOnce(r({result:{claim_id:"c-real"}})).mockResolvedValueOnce(r({result:{}})).mockResolvedValueOnce(r({result:{review_round_id:"rr"}}));v();await screen.findByText("a");fireEvent.click(screen.getByRole("button",{name:"作为本次 claim 来源"}));fireEvent.change(screen.getByLabelText("形成一个由你亲自写下的 claim"),{target:{value:"mine"}});fireEvent.click(screen.getByRole("button",{name:"确认提交检验"}));await waitFor(()=>expect(fetchMock.mock.calls.filter(([u])=>String(u).includes("forge-provenance"))).toHaveLength(1));const p=JSON.parse(fetchMock.mock.calls.find(([u])=>String(u).includes("forge-provenance"))![1].body);expect(p).toMatchObject({claim_id:"c-real",capture_id:"cap",release_id:"r",expected_sequence:0});expect(p.command_id).toBeTruthy();expect(fetchMock.mock.calls.findIndex(([u])=>String(u).includes("forge-provenance"))).toBeLessThan(fetchMock.mock.calls.findIndex(([u])=>String(u).includes("review-rounds")))})
 it("valid skip hint creates lineage",async()=>{fetchMock.mockResolvedValueOnce(r(desk("a",[ref]))).mockResolvedValueOnce(r({result:{claim_id:"c"}})).mockResolvedValueOnce(r({result:{}})).mockResolvedValueOnce(r({result:{review_round_id:"rr"}}));v("a","r");await screen.findByText("a");await waitFor(()=>expect(screen.getByRole("button",{name:"不作为本次 claim 来源"})).toBeInTheDocument());fireEvent.change(screen.getByLabelText("形成一个由你亲自写下的 claim"),{target:{value:"mine"}});fireEvent.click(screen.getByRole("button",{name:"确认提交检验"}));await waitFor(()=>expect(fetchMock.mock.calls.some(([u])=>String(u).includes("forge-provenance"))).toBe(true))})
 it("invalid and removed hints never create lineage",async()=>{fetchMock.mockResolvedValue(r(desk("a",[])));v("a","missing");await screen.findByText("a");fireEvent.change(screen.getByLabelText("形成一个由你亲自写下的 claim"),{target:{value:"mine"}});fireEvent.click(screen.getByRole("button",{name:"确认提交检验"}));await waitFor(()=>expect(fetchMock.mock.calls.some(([u])=>String(u).endsWith("/claims"))).toBe(true));expect(fetchMock.mock.calls.some(([u])=>String(u).includes("forge-provenance"))).toBe(false)})
 it("A source cannot lineage B after route transition",async()=>{let resolveA!: (x:Response)=>void;fetchMock.mockImplementation((u:unknown)=>{const p=String(u);if(p.endsWith("/workspaces/a"))return new Promise<Response>(x=>resolveA=x);if(p.endsWith("/workspaces/b"))return Promise.resolve(r(desk("b",[])));if(p.endsWith("/claims"))return Promise.resolve(r({result:{claim_id:"bclaim"}}));if(p.includes("review-rounds"))return Promise.resolve(r({result:{review_round_id:"rr"}}));return Promise.resolve(r({}))});const x=v("a","r");x.rerender(<AppRouter><WorkspaceDesk workspaceId="b"/></AppRouter>);await screen.findByText("b");resolveA(r(desk("a",[ref])));fireEvent.change(screen.getByLabelText("形成一个由你亲自写下的 claim"),{target:{value:"b mine"}});fireEvent.click(screen.getByRole("button",{name:"确认提交检验"}));await waitFor(()=>expect(fetchMock.mock.calls.some(([u])=>String(u).endsWith("/claims"))).toBe(true));expect(fetchMock.mock.calls.some(([u])=>String(u).includes("forge-provenance"))).toBe(false)})
})
