import { fireEvent, render, screen, waitFor } from "@testing-library/react"
import { beforeEach, describe, expect, it, vi } from "vitest"
import { WorkspaceDesk } from "./WorkspaceDesk"
import { AppRouter } from "../../../router"
const fetchMock = vi.fn(); vi.stubGlobal("fetch", fetchMock)
const base = { id: "w", question: { version_id: "q", text: "Q" }, sequence: 9, note: { id: "n", note_id: "n", revision_id: "rev", text: "abcdef", sequence: 9 }, note_revisions: [], anchors: [], claims: [], review_rounds: [], pending_challenges: [] }
const r = (x: unknown, status=200) => new Response(JSON.stringify(x), { status })
function view(){ return render(<AppRouter><WorkspaceDesk workspaceId="w" /></AppRouter>) }
describe("workspace race regressions", () => { beforeEach(()=>fetchMock.mockReset())
 it("save A pending then type B leaves B after A resolves", async()=>{let resolve!: (x:Response)=>void; fetchMock.mockResolvedValueOnce(r(base)).mockImplementationOnce(()=>new Promise(x=>resolve=x)).mockResolvedValue(r(base)); view(); const n=await screen.findByLabelText("探索稿"); fireEvent.change(n,{target:{value:"A"}}); fireEvent.click(screen.getByRole("button",{name:"保存当前版本"})); fireEvent.change(n,{target:{value:"B"}}); resolve(r({commit_position:1,event_ids:[],result:{},fragment:{...base,note:{...base.note,text:"A"}}})); await waitFor(()=>expect((screen.getByLabelText("探索稿") as HTMLTextAreaElement).value).toBe("B")) })
 it("editing after saved revision disables anchor",async()=>{fetchMock.mockResolvedValue(r(base));view();const n=await screen.findByLabelText("探索稿") as HTMLTextAreaElement;n.setSelectionRange(1,3);fireEvent.select(n);expect(screen.getByRole("button",{name:"保留所选片段"})).toBeEnabled();fireEvent.change(n,{target:{value:"x"}});expect(screen.getByRole("button",{name:"保留所选片段"})).toBeDisabled()})
 it("claim success then review retry reuses exact review envelope",async()=>{fetchMock.mockResolvedValueOnce(r(base)).mockResolvedValueOnce(r({commit_position:1,event_ids:[],result:{claim_id:"c",aggregate_sequences:{c:4}}})).mockResolvedValueOnce(r({detail:"net"},503)).mockResolvedValueOnce(r({commit_position:2,event_ids:[],result:{review_round_id:"rr"}}));view();await screen.findByText("Q");fireEvent.change(screen.getByLabelText("形成一个由你亲自写下的 claim"),{target:{value:"m"}});fireEvent.click(screen.getByRole("button",{name:"确认提交检验"}));await screen.findByRole("alert");fireEvent.click(screen.getByRole("button",{name:"重新形成挑战"}));await waitFor(()=>expect(fetchMock.mock.calls.filter(([u])=>String(u).endsWith("/claims"))).toHaveLength(1));const rs=fetchMock.mock.calls.filter(([u])=>String(u).endsWith("/review-rounds"));expect(rs).toHaveLength(2);expect(rs[0][1].body).toBe(rs[1][1].body)})
 it("double click creates one claim and one review",async()=>{let resolve!: (x:Response)=>void;fetchMock.mockResolvedValueOnce(r(base)).mockImplementationOnce(()=>new Promise(x=>resolve=x)).mockResolvedValueOnce(r({commit_position:2,event_ids:[],result:{review_round_id:"rr"}}));view();await screen.findByText("Q");fireEvent.change(screen.getByLabelText("形成一个由你亲自写下的 claim"),{target:{value:"m"}});const b=screen.getByRole("button",{name:"确认提交检验"});fireEvent.click(b);fireEvent.click(b);resolve(r({commit_position:1,event_ids:[],result:{claim_id:"c",aggregate_sequences:{c:4}}}));await waitFor(()=>expect(fetchMock.mock.calls.filter(([u])=>String(u).endsWith("/claims"))).toHaveLength(1));expect(fetchMock.mock.calls.filter(([u])=>String(u).endsWith("/review-rounds"))).toHaveLength(1)})
 it("409 reapply uses fresh command and latest sequence",async()=>{const latest={...base,sequence:15};fetchMock.mockResolvedValueOnce(r(base)).mockResolvedValueOnce(r({detail:"stale"},409)).mockResolvedValueOnce(r(latest)).mockResolvedValueOnce(r({commit_position:1,event_ids:[],result:{claim_id:"c",aggregate_sequences:{c:2}}})).mockResolvedValueOnce(r({commit_position:2,event_ids:[],result:{review_round_id:"rr"}}));view();await screen.findByText("Q");fireEvent.change(screen.getByLabelText("形成一个由你亲自写下的 claim"),{target:{value:"m"}});fireEvent.click(screen.getByRole("button",{name:"确认提交检验"}));await screen.findByRole("button",{name:"按最新版本重新应用"});fireEvent.click(screen.getByRole("button",{name:"按最新版本重新应用"}));fireEvent.click(screen.getByRole("button",{name:"确认提交检验"}));await waitFor(()=>expect(fetchMock.mock.calls.filter(([u])=>String(u).endsWith("/claims"))).toHaveLength(2));const cs=fetchMock.mock.calls.filter(([u])=>String(u).endsWith("/claims"));const a=JSON.parse(cs[0][1].body),b=JSON.parse(cs[1][1].body);expect(a.command_id).not.toBe(b.command_id);expect(b.expected_sequence).toBe(0)})
})
