import { fireEvent, render, screen, waitFor } from "@testing-library/react"
import { beforeEach, describe, expect, it, vi } from "vitest"
import { WorkspaceDesk } from "./WorkspaceDesk"
import { AppRouter } from "../../../router"

const fetchMock = vi.fn(); vi.stubGlobal("fetch", fetchMock)
const base = { id: "w", question: { version_id: "q", text: "Q" }, sequence: 9, note: { id: "n", note_id: "n", revision_id: "rev", text: "abcdef", sequence: 9 }, note_revisions: [], anchors: [], claims: [], review_rounds: [], pending_challenges: [] }
const response = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status })
function view(id = "w") { return render(<AppRouter><WorkspaceDesk workspaceId={id} /></AppRouter>) }
describe("workspace desk native regression", () => {
 beforeEach(() => fetchMock.mockReset())
 it("submits exact textarea selection against current revision and disables empty selection", async () => { fetchMock.mockResolvedValueOnce(response(base)).mockResolvedValueOnce(response({ commit_position: 1, event_ids: [], result: { anchor_id: "a" } })).mockResolvedValueOnce(response(base)); view(); const note = await screen.findByLabelText("探索稿") as HTMLTextAreaElement; expect(screen.getByRole("button", { name: "保留所选片段" })).toBeDisabled(); note.setSelectionRange(1, 4); fireEvent.select(note); fireEvent.click(screen.getByRole("button", { name: "保留所选片段" })); await waitFor(() => expect(fetchMock).toHaveBeenCalledTimes(3)); const [, init] = fetchMock.mock.calls[1]; expect(JSON.parse(init.body)).toMatchObject({ expected_sequence: 9, note_id: "n", note_revision_id: "rev", start: 1, end: 4, selected_text: "bcd" }) })
 it("409 reloads the authoritative workspace rather than regenerating a claim intent", async () => { const authoritative = { ...base, sequence: 10, question: { version_id: "q-authoritative", text: "authoritative" } }; fetchMock.mockResolvedValueOnce(response(base)).mockResolvedValueOnce(response({ detail: "stale" }, 409)).mockResolvedValueOnce(response(authoritative)); view(); await screen.findByText("Q"); fireEvent.change(screen.getByLabelText("形成一个由你亲自写下的 claim"), { target: { value: "mine" } }); fireEvent.click(screen.getByRole("button", { name: "确认提交检验" })); await screen.findByText("authoritative"); expect(fetchMock.mock.calls.filter(([u]) => String(u).endsWith("/claims"))).toHaveLength(1) })
 it("late workspace A response cannot overwrite workspace B", async () => { let resolveA!: (value: Response) => void; fetchMock.mockImplementation((url: string) => String(url).endsWith("/workspaces/a") ? new Promise<Response>(resolve => { resolveA = resolve }) : Promise.resolve(response({ ...base, id: "b", question: { version_id: "q-b", text: "B" } }))); const rendered = view("a"); rendered.rerender(<AppRouter><WorkspaceDesk workspaceId="b" /></AppRouter>); await screen.findByText("B"); resolveA(response({ ...base, id: "a", question: { version_id: "q-a", text: "A" } })); await new Promise(resolve => setTimeout(resolve, 0)); expect(screen.queryByText("A")).not.toBeInTheDocument() })
 it("keeps returned fragment visible when reconciliation GET fails", async () => { const fragment = { ...base, question: { version_id: "q-returned", text: "returned" }, sequence: 12 }; fetchMock.mockResolvedValueOnce(response(base)).mockResolvedValueOnce(response({ commit_position: 2, event_ids: [], result: { note_id: "n", note_revision_id: "rev2" }, fragment })).mockResolvedValueOnce(response({ detail: "offline" }, 503)); view(); await screen.findByText("Q"); fireEvent.click(screen.getByRole("button", { name: "保存当前版本" })); await screen.findByText("returned"); expect(screen.getByRole("button", { name: "保存当前版本" })).toBeEnabled() })
})
