import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
import { AppRouter } from "../../../router"
import { WorkspaceDesk } from "./WorkspaceDesk"

const fetchMock = vi.fn(); vi.stubGlobal("fetch", fetchMock)
const response = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status })
const base = { id: "w", question: { version_id: "q", text: "Q" }, sequence: 9, note: null, note_revisions: [], anchors: [], claims: [], review_rounds: [], pending_challenges: [], park_release_refs: [{ id: "r", capture_id: "p", provisional_role: "exploration" }] }
afterEach(() => cleanup())
beforeEach(() => fetchMock.mockReset())
function view(path = "/workspaces/w") { window.history.replaceState({}, "", path); return render(<AppRouter><WorkspaceDesk workspaceId="w" forgeReleaseRefId={path.includes("/forge/") ? "r" : undefined} /></AppRouter>) }

describe("release provenance", () => {
  it("renders source from reloaded projection, not query transport", async () => { fetchMock.mockResolvedValue(response(base)); view(); expect(await screen.findByText(/来自密封 PARK 原件/)).toBeInTheDocument(); expect(screen.getByRole("link", { name: "从此原件锻造自写 claim" })).toHaveAttribute("href", "/workspaces/w/forge/r") })
  it("bypass creates claim then retains provenance before review", async () => { fetchMock.mockResolvedValueOnce(response(base)).mockResolvedValueOnce(response({ commit_position: 1, event_ids: [], result: { claim_id: "c" } })).mockResolvedValueOnce(response({ commit_position: 2, event_ids: [], result: {} })).mockResolvedValueOnce(response({ commit_position: 3, event_ids: [], result: { review_round_id: "rr" } })); view(); await screen.findByText("Q"); fireEvent.click(screen.getByRole("button", { name: "作为本次 claim 来源" })); fireEvent.change(screen.getByLabelText("形成一个由你亲自写下的 claim"), { target: { value: "mine" } }); fireEvent.click(screen.getByRole("button", { name: "确认提交检验" })); await waitFor(() => expect(fetchMock.mock.calls.filter(([url]) => String(url).includes("forge-provenance"))).toHaveLength(1)); const provenance = fetchMock.mock.calls.find(([url]) => String(url).includes("forge-provenance")); const review = fetchMock.mock.calls.find(([url]) => String(url).includes("review-rounds")); expect(provenance?.[0]).toContain("/workspaces/w/claims/forge-provenance"); expect(review?.[0]).toContain("/claims/c/review-rounds") })
  it("forge retains provenance envelope across retry and ignores stale route", async () => { fetchMock.mockResolvedValueOnce(response(base)).mockResolvedValueOnce(response({ commit_position: 1, event_ids: [], result: { claim_id: "c" } })).mockResolvedValueOnce(response({ detail: "offline" }, 503)).mockResolvedValueOnce(response({ commit_position: 2, event_ids: [], result: {} })).mockResolvedValueOnce(response({ commit_position: 3, event_ids: [], result: { review_round_id: "rr" } })); view("/workspaces/w/forge/r"); const field = await screen.findByLabelText("由你亲自写下的 claim"); fireEvent.change(field, { target: { value: "mine" } }); fireEvent.click(screen.getByRole("button", { name: "提交检验" })); await screen.findByRole("alert"); fireEvent.click(screen.getByRole("button", { name: "提交检验" })); await waitFor(() => expect(fetchMock.mock.calls.filter(([url]) => String(url).includes("/workspaces/w/claims/forge-provenance")).length).toBeGreaterThanOrEqual(2)); const calls = fetchMock.mock.calls.filter(([url]) => String(url).includes("/workspaces/w/claims/forge-provenance")).slice(0, 2); expect(calls[0][1].body).toBe(calls[1][1].body) })
})
