import { useEffect, useRef, useState, type FormEvent } from "react"
import { command, researchUniverse } from "../api"
import type { CommandEnvelope, ConclusionType, MaterialPurpose, ParkReleaseRef, WorkspaceDesk as Desk, WorkspacePosition } from "../types"
import { ReleaseForge } from "./ReleaseForge"
import { useNavigation } from "../../../router"

const POSITION_LABELS: Record<WorkspacePosition, string> = { exploring: "探索中", paused: "已暂停", concluded: "已结晶", branched: "已分支", absorbed: "已并入" }
const CONCLUSION_OPTIONS: { type: ConclusionType; label: string; note?: string }[] = [
  { type: "tentative_answer", label: "暂时回答", note: "这是一段可检验的回答" },
  { type: "negated_path", label: "否定路径", note: "这条路被证伪或放弃了" },
  { type: "boundary", label: "划出边界", note: "问题需要收窄或改写" },
  { type: "key_unknown", label: "关键未知", note: "卡在某个关键未知上" },
  { type: "deferred", label: "暂缓条件", note: "现在先不投入，写下何时回来" },
  { type: "split_or_turn", label: "拆分／转向", note: "这一支需要拆开或拐弯" },
]

type Selection = { start: number; end: number; selected_text: string }
type ClaimIntent = { claim: CommandEnvelope & { text: string }; claimId?: string; provenance?: CommandEnvelope & { claim_id: string; capture_id: string; release_id: string }; review?: CommandEnvelope }
export function WorkspaceDesk({ workspaceId, forgeReleaseRefId, sourceReleaseId }: { workspaceId: string; forgeReleaseRefId?: string; sourceReleaseId?: string }) {
  const { navigate } = useNavigation(); const [desk, setDesk] = useState<Desk | null>(null); const [sourceRef, setSourceRef] = useState<ParkReleaseRef | undefined>(); const [note, setNote] = useState(""); const [selected, setSelected] = useState<Selection>(); const [claim, setClaim] = useState(""); const [error, setError] = useState<string>(); const [conflict, setConflict] = useState(false); const [savePending, setSavePending] = useState(false); const draftGeneration = useRef(0); const noteCommand = useRef<(CommandEnvelope & { text: string }) | undefined>(undefined); const anchorCommand = useRef<(CommandEnvelope & { note_id: string; note_revision_id: string; start: number; end: number; selected_text: string }) | undefined>(undefined); const claimIntent = useRef<ClaimIntent | undefined>(undefined); const claimFlight = useRef<Promise<void> | undefined>(undefined); const routeGeneration = useRef(0); const routeId = useRef(workspaceId); const [claimPending, setClaimPending] = useState(false); const [claimStage, setClaimStage] = useState<"idle" | "saving-claim" | "generating-challenge" | "review-error">("idle"); const [materialExcerpt, setMaterialExcerpt] = useState(""); const [materialSource, setMaterialSource] = useState(""); const [materialPurpose, setMaterialPurpose] = useState<MaterialPurpose>("evidence"); const [materialUnparsable, setMaterialUnparsable] = useState(false); const [materialPending, setMaterialPending] = useState(false); const materialCommand = useRef<(CommandEnvelope & { excerpt: string; source_locator?: string | null; parse_status: "parsed" | "failed"; purpose: MaterialPurpose }) | undefined>(undefined); const [crystallizing, setCrystallizing] = useState(false); const [conclusionText, setConclusionText] = useState(""); const [conclusionType, setConclusionType] = useState<ConclusionType | null>(null); const [revivalCondition, setRevivalCondition] = useState(""); const [concluding, setConcluding] = useState(false); const [branchOpen, setBranchOpen] = useState(false); const [branchQuestion, setBranchQuestion] = useState(""); const [branchReason, setBranchReason] = useState(""); const [branchPending, setBranchPending] = useState(false); const [absorbOpen, setAbsorbOpen] = useState(false); const [absorbTarget, setAbsorbTarget] = useState(""); const [absorbReason, setAbsorbReason] = useState(""); const [absorbPending, setAbsorbPending] = useState(false); const [impactOpen, setImpactOpen] = useState(false); const [impactChoice, setImpactChoice] = useState<"stay" | "crystallize" | "rephrase">("stay"); const [impactBusy, setImpactBusy] = useState(false);
  async function load(accept = () => true) { try { const value = await researchUniverse.desk(workspaceId); if (accept()) { setDesk(value); if (!noteCommand.current && draftGeneration.current === 0) setNote(value.note?.text ?? ""); setError(undefined) } } catch (e) { if (accept()) setError(e instanceof Error ? e.message : "读取失败") } }
  useEffect(() => { let live = true; routeGeneration.current++; routeId.current = workspaceId; noteCommand.current = undefined; anchorCommand.current = undefined; claimIntent.current = undefined; claimFlight.current = undefined; materialCommand.current = undefined; setSavePending(false); setClaimPending(false); setMaterialPending(false); setMaterialExcerpt(""); setMaterialSource(""); setMaterialPurpose("evidence"); setMaterialUnparsable(false); setSourceRef(undefined); setClaimStage("idle"); setConflict(false); setDesk(null); setError(undefined); setSelected(undefined); setCrystallizing(false); setConclusionText(""); setConclusionType(null); setRevivalCondition(""); setConcluding(false); setBranchOpen(false); setBranchQuestion(""); setBranchReason(""); setBranchPending(false); setAbsorbOpen(false); setAbsorbTarget(""); setAbsorbReason(""); setAbsorbPending(false); setImpactOpen(false); setImpactChoice("stay"); setImpactBusy(false); draftGeneration.current = 0; void load(() => live); return () => { live = false } }, [workspaceId])
  function editNote(text: string) { draftGeneration.current++; setNote(text); setSelected(undefined); noteCommand.current = undefined }
  const isCurrent = (generation: number, id: string) => generation === routeGeneration.current && id === routeId.current
  async function saveNote() { if (!desk || savePending) return; const currentGeneration = routeGeneration.current, currentId = workspaceId; const generation = draftGeneration.current; noteCommand.current ??= command({ text: note }, desk.sequence); setSavePending(true); try { const result = await researchUniverse.saveNote(currentId, noteCommand.current); if (!isCurrent(currentGeneration, currentId)) return; noteCommand.current = undefined; const fragment = result.fragment as Desk | undefined; if (fragment?.id) { setDesk(fragment); if (draftGeneration.current === generation) { setNote(fragment.note?.text ?? note); draftGeneration.current = 0 } void load(() => isCurrent(currentGeneration, currentId)) } else void load(() => isCurrent(currentGeneration, currentId)) } catch (e) { if (!isCurrent(currentGeneration, currentId)) return; setError(e instanceof Error ? e.message : "保存失败"); if ((e as { status?: number }).status === 409) { noteCommand.current = undefined; setConflict(true); void load(() => isCurrent(currentGeneration, currentId)) } } finally { if (isCurrent(currentGeneration, currentId)) setSavePending(false) } }
  async function anchor() { if (!desk?.note || !selected || note !== desk.note.text || savePending) return; const currentGeneration = routeGeneration.current, currentId = workspaceId; anchorCommand.current ??= command({ note_id: desk.note.note_id ?? desk.note.id, note_revision_id: desk.note.revision_id, ...selected }, desk.sequence); try { await researchUniverse.createAnchor(currentId, anchorCommand.current); if (!isCurrent(currentGeneration, currentId)) return; anchorCommand.current = undefined; void load(() => isCurrent(currentGeneration, currentId)) } catch (e) { if (!isCurrent(currentGeneration, currentId)) return; setError(e instanceof Error ? e.message : "锚点失败"); if ((e as { status?: number }).status === 409) { anchorCommand.current = undefined; setConflict(true); void load(() => isCurrent(currentGeneration, currentId)) } } }
  function forge(e: FormEvent) { e.preventDefault(); if (!desk || !claim.trim() || claimFlight.current) return; const currentGeneration = routeGeneration.current, currentId = workspaceId; claimIntent.current ??= { claim: command({ text: claim.trim() }, 0) }; setClaimPending(true); setClaimStage(claimIntent.current.claimId ? "generating-challenge" : "saving-claim"); claimFlight.current = (async () => { try { if (!claimIntent.current!.claimId) { const made = await researchUniverse.createClaim(currentId, claimIntent.current!.claim); if (!isCurrent(currentGeneration, currentId)) return; claimIntent.current!.claimId = made.result.claim_id; if (sourceRef && !claimIntent.current!.provenance) claimIntent.current!.provenance = command({ claim_id: made.result.claim_id, capture_id: sourceRef.capture_id, release_id: sourceRef.id }, 0) } if (claimIntent.current!.provenance) { await researchUniverse.forgeProvenance(currentId, claimIntent.current!.provenance); if (!isCurrent(currentGeneration, currentId)) return } if (!claimIntent.current!.review) { claimIntent.current!.review = command({}, 0); setClaimStage("generating-challenge") } const review = await researchUniverse.startReview(claimIntent.current!.claimId!, claimIntent.current!.review!); if (!isCurrent(currentGeneration, currentId)) return; claimIntent.current = undefined; navigate(`/review-rounds/${review.result.review_round_id}`) } catch (x) { if (!isCurrent(currentGeneration, currentId)) return; setError(claimIntent.current?.claimId ? "主张已保存，但挑战尚未形成。可以重试，不会重复创建主张。" : (x instanceof Error ? x.message : "提交失败")); setClaimStage(claimIntent.current?.claimId ? "review-error" : "idle"); if ((x as { status?: number }).status === 409) { claimIntent.current = undefined; setConflict(true); void load(() => isCurrent(currentGeneration, currentId)) } } finally { if (isCurrent(currentGeneration, currentId)) { claimFlight.current = undefined; setClaimPending(false) } } })() }
  function reapply() { if (!desk) return; setConflict(false); noteCommand.current = undefined; anchorCommand.current = undefined; claimIntent.current = undefined; materialCommand.current = undefined; setError(undefined) }
  async function addMaterial() {
    if (!desk || materialPending || !materialExcerpt.trim()) return
    const currentGeneration = routeGeneration.current, currentId = workspaceId
    materialCommand.current ??= command({ excerpt: materialExcerpt.trim(), source_locator: materialSource.trim() || null, parse_status: materialUnparsable ? "failed" : "parsed", purpose: materialPurpose }, 0)
    setMaterialPending(true)
    try {
      await researchUniverse.addMaterial(currentId, materialCommand.current)
      if (!isCurrent(currentGeneration, currentId)) return
      materialCommand.current = undefined
      setMaterialExcerpt(""); setMaterialSource(""); setMaterialPurpose("evidence"); setMaterialUnparsable(false)
      void load(() => isCurrent(currentGeneration, currentId))
    } catch (e) {
      if (!isCurrent(currentGeneration, currentId)) return
      setError(e instanceof Error ? e.message : "带入材料失败")
      if ((e as { status?: number }).status === 409) { materialCommand.current = undefined; setConflict(true); void load(() => isCurrent(currentGeneration, currentId)) }
    } finally { if (isCurrent(currentGeneration, currentId)) setMaterialPending(false) }
  }
  // Slice 5 — lifecycle actions
  async function lifecycleAction(action: "pause" | "reopen") {
    if (!desk) return
    const currentGeneration = routeGeneration.current, currentId = workspaceId
    try {
      if (action === "pause") await researchUniverse.pauseWorkspace(currentId, command({ user_reason: null }, desk.sequence))
      else await researchUniverse.reopenWorkspace(currentId, command({ user_reason: null }, desk.sequence))
      if (!isCurrent(currentGeneration, currentId)) return
      void load(() => isCurrent(currentGeneration, currentId))
    } catch (e) { if (!isCurrent(currentGeneration, currentId)) return; setError(e instanceof Error ? e.message : (action === "pause" ? "暂停失败" : "重开失败")); if ((e as { status?: number }).status === 409) { setConflict(true); void load(() => isCurrent(currentGeneration, currentId)) } }
  }
  async function conclude() {
    if (!desk || concluding || !conclusionType || !conclusionText.trim() || (conclusionType === "deferred" && !revivalCondition.trim())) return
    const currentGeneration = routeGeneration.current, currentId = workspaceId
    setConcluding(true)
    try {
      await researchUniverse.concludeWorkspace(currentId, command({ conclusion_type: conclusionType, conclusion_text: conclusionText.trim(), user_reason: null, basis_refs: [], revival_condition: conclusionType === "deferred" ? revivalCondition.trim() : null }, desk.sequence))
      if (!isCurrent(currentGeneration, currentId)) return
      setCrystallizing(false); setConclusionText(""); setConclusionType(null); setRevivalCondition(""); setImpactOpen(true)
      void load(() => isCurrent(currentGeneration, currentId))
    } catch (e) { if (!isCurrent(currentGeneration, currentId)) return; setError(e instanceof Error ? e.message : "结晶失败"); if ((e as { status?: number }).status === 409) { setConflict(true); void load(() => isCurrent(currentGeneration, currentId)) } } finally { if (isCurrent(currentGeneration, currentId)) setConcluding(false) }
  }
  async function branch() {
    if (!desk || branchPending || !branchQuestion.trim() || !branchReason.trim()) return
    const currentGeneration = routeGeneration.current, currentId = workspaceId
    setBranchPending(true)
    try {
      const result = await researchUniverse.branchWorkspace(currentId, command({ new_question: branchQuestion.trim(), user_reason: branchReason.trim() }, desk.sequence))
      if (!isCurrent(currentGeneration, currentId)) return
      setBranchOpen(false); setBranchQuestion(""); setBranchReason("")
      navigate(`/workspaces/${result.result.successor_workspace_id}`)
    } catch (e) { if (!isCurrent(currentGeneration, currentId)) return; setError(e instanceof Error ? e.message : "分支失败"); if ((e as { status?: number }).status === 409) { setConflict(true); void load(() => isCurrent(currentGeneration, currentId)) } } finally { if (isCurrent(currentGeneration, currentId)) setBranchPending(false) }
  }
  async function absorb() {
    if (!desk || absorbPending || !absorbTarget.trim() || !absorbReason.trim()) return
    const currentGeneration = routeGeneration.current, currentId = workspaceId
    setAbsorbPending(true)
    try {
      await researchUniverse.absorbWorkspace(currentId, command({ target_workspace_id: absorbTarget.trim(), user_reason: absorbReason.trim() }, desk.sequence))
      if (!isCurrent(currentGeneration, currentId)) return
      setAbsorbOpen(false); setAbsorbTarget(""); setAbsorbReason("")
      void load(() => isCurrent(currentGeneration, currentId))
    } catch (e) { if (!isCurrent(currentGeneration, currentId)) return; setError(e instanceof Error ? e.message : "吸收失败"); if ((e as { status?: number }).status === 409) { setConflict(true); void load(() => isCurrent(currentGeneration, currentId)) } } finally { if (isCurrent(currentGeneration, currentId)) setAbsorbPending(false) }
  }
  async function confirmImpact() {
    if (!desk || impactBusy) return
    const firstLink = desk.direction_links?.[0]; if (!firstLink || impactChoice === "stay") { setImpactOpen(false); return }
    const currentGeneration = routeGeneration.current, currentId = workspaceId
    setImpactBusy(true)
    try {
      if (impactChoice === "crystallize") {
        if (!desk.conclusion) return
        await researchUniverse.attachCrystallization(firstLink.direction_id, command({ workspace_id: currentId, conclusion_id: desk.conclusion.id, user_reason: null }, 0))
      } else {
        navigate(`/directions/${firstLink.direction_id}?rephrase=1&source_conclusion=${encodeURIComponent(desk.conclusion?.id ?? "")}`)
      }
      if (!isCurrent(currentGeneration, currentId)) return
      setImpactOpen(false)
      if (impactChoice === "crystallize") void load(() => isCurrent(currentGeneration, currentId))
    } catch (e) { if (!isCurrent(currentGeneration, currentId)) return; setError(e instanceof Error ? e.message : "方向影响未保存"); if ((e as { status?: number }).status === 409) { setConflict(true); void load(() => isCurrent(currentGeneration, currentId)) } } finally { if (isCurrent(currentGeneration, currentId)) setImpactBusy(false) }
  }
  useEffect(() => { const hinted = sourceReleaseId && desk ? (desk.park_release_refs ?? []).find(item => item.id === sourceReleaseId) : undefined; setSourceRef(current => current?.id === hinted?.id ? current : hinted) }, [desk, sourceReleaseId, workspaceId])
  if (!desk) return <section className="ru-state" role={error ? "alert" : undefined}>{error ?? "正在展开问题工作区…"}{error && <button className="ru-ink-button" onClick={() => void load()}>重试</button>}</section>
  const pending = desk.pending_challenges[0], anchorReady = Boolean(selected && desk.note && note === desk.note.text && !savePending), releaseRefs = desk.park_release_refs ?? [], pendingStatusLabel = pending?.status === "answered" ? "已回应 · 待裁决" : "待回应 challenge"
  const forgeRef = forgeReleaseRefId ? releaseRefs.find(item => item.id === forgeReleaseRefId) : undefined
  if (forgeReleaseRefId && !forgeRef) return <section className="ru-state" role="alert">未找到这份放行引用。<button className="ru-ink-button" onClick={() => navigate(`/workspaces/${workspaceId}`)}>回到工作区</button></section>
  const forging = Boolean(forgeRef)
  const position = desk.user_position ?? "exploring"
  const firstLink = desk.direction_links?.[0]
  const verdicts = desk.review_rounds.filter(r => r.verdict)
  const confirmedFacts = desk.confirmed_facts ?? []
  const pendingItems = desk.pending_challenges.filter(c => c.status === "pending")
  const lifecycleControls = <div className="ru-lifecycle" aria-label="工作区位置与生命周期"><span className="ru-position-tag">位置：{POSITION_LABELS[position]}</span>{position === "exploring" && <><button className="ru-quiet-button" onClick={() => void lifecycleAction("pause")}>暂停探索</button><button className="ru-quiet-button" onClick={() => setCrystallizing(true)}>确认这次探索的位置</button><button className="ru-quiet-button" onClick={() => setBranchOpen(true)}>分支</button><button className="ru-quiet-button" onClick={() => setAbsorbOpen(true)}>吸收</button></>}{(position === "paused" || position === "concluded") && <button className="ru-quiet-button" onClick={() => void lifecycleAction("reopen")}>重开</button>}{position === "concluded" && <><button className="ru-quiet-button" onClick={() => setImpactOpen(true)}>方向影响</button><button className="ru-quiet-button" onClick={() => setBranchOpen(true)}>分支</button><button className="ru-quiet-button" onClick={() => setAbsorbOpen(true)}>吸收</button></>}</div>
  const crystallizationDesk = crystallizing ? <section className="ru-crystallization" aria-labelledby="crystallization-title"><p className="ru-kicker">确认这次探索的位置</p><h2 id="crystallization-title">结晶台</h2><p className="ru-reading-copy">这一问题：{desk.question.text}</p><div className="ru-crystal-ledger"><p className="ru-kicker">已发生的事实</p>{verdicts.map(r => <p key={r.id} className="ru-ledger-item">{r.claim_snapshot.text} · 裁决：{r.verdict!.verdict_type}</p>)}{confirmedFacts.map(f => <p key={f.id} className="ru-ledger-item">已确认取证：{f.material_anchor.excerpt} · {f.relation}</p>)}{pendingItems.map(c => <p key={c.id} className="ru-ledger-item ru-pending-ledger">仍挂起：{c.attack_surface}</p>)}{verdicts.length === 0 && confirmedFacts.length === 0 && pendingItems.length === 0 && <p className="ru-edge-empty">还没有已发生的事实。</p>}</div><label htmlFor="conclusion-text">我的探索结论</label><textarea id="conclusion-text" className="ru-conclusion-text" value={conclusionText} onChange={(e) => setConclusionText(e.target.value)} placeholder="亲写这一支探索的结论，Cui 不会替你总结。" required /><fieldset className="ru-conclusion-types"><legend>这次结晶属于</legend>{CONCLUSION_OPTIONS.map(opt => <label key={opt.type}><input type="radio" name="conclusion-type" checked={conclusionType === opt.type} onChange={() => setConclusionType(opt.type)} /> <span>{opt.label}</span>{opt.note && <small>{opt.note}</small>}</label>)}</fieldset>{conclusionType === "deferred" && <label htmlFor="revival-condition" className="ru-revival-label">未来重开条件（必填）</label>}{conclusionType === "deferred" && <input id="revival-condition" className="ru-revival-input" value={revivalCondition} onChange={(e) => setRevivalCondition(e.target.value)} placeholder="何时、什么条件下再回来" required />}<p className="ru-challenge-note">仍有待回应的事实不会阻止结晶；它们仍然可见。</p><div className="ru-crystal-actions"><button className="ru-quiet-button" onClick={() => setCrystallizing(false)}>保留为继续探索</button><button className="ru-ink-button ru-active" disabled={concluding || !conclusionType || !conclusionText.trim() || (conclusionType === "deferred" && !revivalCondition.trim())} onClick={() => void conclude()}>{concluding ? "正在记录…" : "确认结晶"}</button></div></section> : null
  const directionImpact = impactOpen && firstLink ? <section className="ru-direction-impact" aria-labelledby="impact-title"><p className="ru-kicker">方向影响台</p><h2 id="impact-title">已确认本次探索结论</h2><p className="ru-reading-copy">它关联的方向：{firstLink.direction_proposition ?? "这条方向"}</p><fieldset><legend>这次结晶对它：</legend><label><input type="radio" name="impact" checked={impactChoice === "stay"} onChange={() => setImpactChoice("stay")} /> 只留在这次探索中</label><label><input type="radio" name="impact" checked={impactChoice === "crystallize"} onChange={() => setImpactChoice("crystallize")} /> 成为方向的一项结晶</label><label><input type="radio" name="impact" checked={impactChoice === "rephrase"} onChange={() => setImpactChoice("rephrase")} /> 促使我重述方向命题</label></fieldset><div className="ru-crystal-actions"><button className="ru-quiet-button" onClick={() => setImpactOpen(false)}>暂不决定</button><button className="ru-ink-button ru-active" disabled={impactBusy} onClick={() => void confirmImpact()}>确认</button></div></section> : null
  const branchForm = branchOpen ? <section className="ru-lifecycle-form" aria-labelledby="branch-title"><p className="ru-kicker">分支</p><h2 id="branch-title">把这个探索拆出一条后继问题</h2><p className="ru-reading-copy">Cui 不会替你推断要开什么问题；由你写出后继问题与理由。</p><label htmlFor="branch-question">后继问题</label><textarea id="branch-question" className="ru-conclusion-text" value={branchQuestion} onChange={(e) => setBranchQuestion(e.target.value)} placeholder="分支的新问题…" required /><label htmlFor="branch-reason">为什么分支</label><input id="branch-reason" className="ru-revival-input" value={branchReason} onChange={(e) => setBranchReason(e.target.value)} placeholder="写理由" required /><div className="ru-crystal-actions"><button className="ru-quiet-button" onClick={() => { setBranchOpen(false); setBranchQuestion(""); setBranchReason("") }}>取消</button><button className="ru-ink-button ru-active" disabled={branchPending || !branchQuestion.trim() || !branchReason.trim()} onClick={() => void branch()}>{branchPending ? "正在分支…" : "确认分支"}</button></div></section> : null
  const absorbForm = absorbOpen ? <section className="ru-lifecycle-form" aria-labelledby="absorb-title"><p className="ru-kicker">吸收</p><h2 id="absorb-title">把这一支并入另一条探索</h2><p className="ru-reading-copy">Cui 不会替你推断要并入哪里；由你写下目标工作区与理由。</p><label htmlFor="absorb-target">并入哪一条工作区</label><input id="absorb-target" className="ru-revival-input" value={absorbTarget} onChange={(e) => setAbsorbTarget(e.target.value)} placeholder="目标工作区" required /><label htmlFor="absorb-reason">为什么并入</label><input id="absorb-reason" className="ru-revival-input" value={absorbReason} onChange={(e) => setAbsorbReason(e.target.value)} placeholder="写理由" required /><div className="ru-crystal-actions"><button className="ru-quiet-button" onClick={() => { setAbsorbOpen(false); setAbsorbTarget(""); setAbsorbReason("") }}>取消</button><button className="ru-ink-button ru-active" disabled={absorbPending || !absorbTarget.trim() || !absorbReason.trim()} onClick={() => void absorb()}>{absorbPending ? "正在并入…" : "确认吸收"}</button></div></section> : null
  const workspaceSurface = <section className="ru-workspace"><header className="ru-question-spine"><p className="ru-kicker">问题工作区 · {POSITION_LABELS[position]}</p><h1>{desk.question.text}</h1>{lifecycleControls}{releaseRefs.map(ref => <p key={ref.id} className="ru-provenance">来自密封 PARK 原件的放行引用 · {ref.provisional_role}{!forging && <> · <a href={`/workspaces/${workspaceId}/forge/${ref.id}`}>从此原件锻造自写 claim</a><button className="ru-quiet-button" onClick={() => setSourceRef(sourceRef?.id === ref.id ? undefined : ref)}>{sourceRef?.id === ref.id ? "不作为本次 claim 来源" : "作为本次 claim 来源"}</button></>}</p>)}</header>{error && <p className="ru-error" role="alert">{error}</p>}{conflict && <button className="ru-quiet-button" onClick={reapply}>按最新版本重新应用</button>}<div className="ru-desk-grid"><div className="ru-exploration"><div className="ru-surface-heading"><span>探索稿</span><small>自由记录观察、猜测和未成形判断。Cui 不会在这里回复，也不会自动把内容升格为 Claim 或证据。</small><button className="ru-quiet-button" disabled={savePending} onClick={() => void saveNote()}>保存当前版本</button></div><textarea aria-label="探索稿" className="ru-note" value={note} onChange={(e) => editNote(e.target.value)} onSelect={(e) => { const t = e.currentTarget; const selected_text = t.value.slice(t.selectionStart, t.selectionEnd); setSelected(note === desk.note?.text && selected_text ? { start: t.selectionStart, end: t.selectionEnd, selected_text } : undefined) }} placeholder="写下观察、猜测、反例或尚未成形的判断。" /><button className="ru-quiet-button" disabled={!anchorReady} onClick={() => void anchor()}>保留所选片段</button>{!forging && <form className="ru-claim-form" onSubmit={forge}><label htmlFor="claim">形成一个由你亲自写下的 claim</label><textarea id="claim" value={claim} disabled={claimPending || Boolean(claimIntent.current?.claimId)} onChange={(e) => { setClaim(e.target.value); if (!claimPending) claimIntent.current = undefined }} placeholder="你究竟在断言什么？" required />{claimStage !== "idle" && <p className="ru-claim-progress" aria-live="polite">{claimStage === "saving-claim" ? "正在保存主张…" : claimStage === "generating-challenge" ? "主张已保存，Cui 正在形成挑战…" : "主张已保存，挑战尚未形成。"}</p>}<button className="ru-ink-button" disabled={claimPending}>{claimStage === "review-error" ? "重新形成挑战" : claimStage === "saving-claim" ? "正在保存主张…" : claimStage === "generating-challenge" ? "Cui 正在形成挑战…" : "确认提交检验"}</button></form>}</div><aside className="ru-research-edge"><p className="ru-kicker">研究边缘</p>{pending ? <a className="ru-pending-fact" href={`/review-rounds/${pending.review_round_id}`}><span>{pendingStatusLabel}</span><strong>{pending.attack_surface}</strong></a> : <p className="ru-edge-empty">尚无待回应事实。</p>}</aside></div>
  <section className="ru-material-entry" aria-labelledby="material-entry-title"><p className="ru-kicker">带入材料</p><h2 id="material-entry-title">把一份材料带进这个问题</h2><p className="ru-challenge-note">材料先中立进入，保存不可变摘录；进入时它不声明支持或反对任何 claim。</p><form className="ru-material-form" onSubmit={(e) => { e.preventDefault(); void addMaterial() }}><label htmlFor="material-source">来源（可选）</label><input id="material-source" value={materialSource} onChange={(e) => setMaterialSource(e.target.value)} placeholder="标题 / 链接 / 作者……" /><label htmlFor="material-excerpt">摘录或观察</label><textarea id="material-excerpt" value={materialExcerpt} onChange={(e) => setMaterialExcerpt(e.target.value)} placeholder="写下不可变摘录；保存后不可改写。" required /><fieldset className="ru-material-purpose"><legend>它进入这个问题，暂时是：</legend><label><input type="radio" name="material-purpose" checked={materialPurpose === "evidence"} onChange={() => setMaterialPurpose("evidence")} /> 待取证材料</label><label><input type="radio" name="material-purpose" checked={materialPurpose === "reference"} onChange={() => setMaterialPurpose("reference")} /> 只作探索参考</label></fieldset><label className="ru-material-unparsable"><input type="checkbox" checked={materialUnparsable} onChange={(e) => setMaterialUnparsable(e.target.checked)} /> 这段摘录我无法判断</label><button className="ru-ink-button ru-active" disabled={materialPending || !materialExcerpt.trim()}>{materialPending ? "正在带入…" : "带入材料"}</button></form>{(desk.materials?.length ?? 0) > 0 && <div className="ru-materials-list"><p className="ru-kicker">已带入材料</p>{desk.materials!.map((m) => <article key={m.id} className="ru-material-card"><p className="ru-reading-copy">{m.excerpt}</p><p className="ru-provenance">{m.source_locator ?? "无来源定位"} · {m.purpose === "evidence" ? "待取证材料" : "只作探索参考"} · {m.parse_status === "failed" ? "无法判断" : "已解析"}</p></article>)}</div>}</section>
  {crystallizationDesk}
  {directionImpact}
  {branchForm}
  {absorbForm}
  {position === "concluded" && desk.conclusion && <section className="ru-crystallization" aria-labelledby="recorded-conclusion-title"><p className="ru-kicker">已记录的结晶</p><h2 id="recorded-conclusion-title">这一支探索已确认结论</h2><p className="ru-reading-copy">{desk.conclusion.text}</p><p className="ru-provenance">类型：{desk.conclusion.type}{desk.conclusion.revival_condition ? ` · 未来重开条件：${desk.conclusion.revival_condition}` : ""}</p></section>}
  </section>
  return forging ? <div className="ru-forge-layout"><ReleaseForge workspaceId={workspaceId} releaseRef={forgeRef!} />{workspaceSurface}</div> : workspaceSurface
}
