import { fireEvent, render, screen, waitFor } from "@testing-library/react"
import { describe, expect, it, vi } from "vitest"
import { WorkspaceDesk } from "./WorkspaceDesk"
import { AppRouter } from "../../../router"
const fetchMock = vi.fn(); vi.stubGlobal("fetch", fetchMock)
const response = (body: unknown) => new Response(JSON.stringify(body))
const desk = (id: string) => ({ id, question: { version_id: `q-${id}`, text: id }, sequence: id === "b" ? 8 : 1, note: { id: `n-${id}`, note_id: `n-${id}`, revision_id: `r-${id}`, text: "abcdef", sequence: 1 }, note_revisions: [], anchors: [], claims: [], review_rounds: [], pending_challenges: [] })
const ui = (id: string) => <AppRouter><WorkspaceDesk workspaceId={id} /></AppRouter>
const body = (call: unknown[]) => JSON.parse((call[1] as RequestInit).body as string)
describe("workspace mutation route guards", () => {
  it("late note A cannot alter B and B save has a fresh B envelope", async () => { let resolveA!: (x: Response) => void; fetchMock.mockImplementation((url: string) => url.endsWith("/workspaces/a") ? Promise.resolve(response(desk("a"))) : url.endsWith("/workspaces/b") ? Promise.resolve(response(desk("b"))) : url.endsWith("/workspaces/a/notes") ? new Promise(x => { resolveA = x }) : Promise.resolve(response({ result: {}, fragment: desk("b") }))); const view = render(ui("a")); await screen.findByText("a"); fireEvent.click(screen.getByRole("button", { name: "保存当前版本" })); view.rerender(ui("b")); await screen.findByText("b"); resolveA(response({ result: {}, fragment: desk("a") })); await Promise.resolve(); fireEvent.change(screen.getByLabelText("探索稿"), { target: { value: "B text" } }); fireEvent.click(screen.getByRole("button", { name: "保存当前版本" })); await waitFor(() => expect(fetchMock.mock.calls.filter(([u]) => String(u).endsWith("/notes"))).toHaveLength(2)); const calls = fetchMock.mock.calls.filter(([u]) => String(u).endsWith("/notes")); expect(calls[1][0]).toContain("/workspaces/b/notes"); expect(body(calls[1])).toMatchObject({ text: "B text", expected_sequence: 8 }); expect(body(calls[1]).command_id).not.toBe(body(calls[0]).command_id) })
  it("late anchor A cannot alter B and B anchor has fresh B provenance", async () => { let resolveA!: (x: Response) => void; fetchMock.mockImplementation((url: string) => url.endsWith("/workspaces/a") ? Promise.resolve(response(desk("a"))) : url.endsWith("/workspaces/b") ? Promise.resolve(response(desk("b"))) : url.endsWith("/workspaces/a/anchors") ? new Promise(x => { resolveA = x }) : Promise.resolve(response({ result: {} }))); const view = render(ui("a")); const a = await screen.findByLabelText("探索稿") as HTMLTextAreaElement; a.setSelectionRange(1, 2); fireEvent.select(a); fireEvent.click(screen.getByRole("button", { name: "保留所选片段" })); view.rerender(ui("b")); const b = await screen.findByLabelText("探索稿") as HTMLTextAreaElement; resolveA(response({ result: {} })); b.setSelectionRange(2, 5); fireEvent.select(b); fireEvent.click(screen.getByRole("button", { name: "保留所选片段" })); await waitFor(() => expect(fetchMock.mock.calls.filter(([u]) => String(u).endsWith("/anchors"))).toHaveLength(2)); const calls = fetchMock.mock.calls.filter(([u]) => String(u).endsWith("/anchors")); expect(calls[1][0]).toContain("/workspaces/b/anchors"); expect(body(calls[1])).toMatchObject({ note_id: "n-b", note_revision_id: "r-b", start: 2, end: 5, selected_text: "cde" }); expect(body(calls[1]).command_id).not.toBe(body(calls[0]).command_id) })
  it("late claim A cannot alter B and B forge has fresh claim then review", async () => { let resolveA!: (x: Response) => void; fetchMock.mockImplementation((url: string) => url.endsWith("/workspaces/a") ? Promise.resolve(response(desk("a"))) : url.endsWith("/workspaces/b") ? Promise.resolve(response(desk("b"))) : url.endsWith("/workspaces/a/claims") ? new Promise(x => { resolveA = x }) : url.endsWith("/workspaces/b/claims") ? Promise.resolve(response({ result: { claim_id: "cb", aggregate_sequences: { cb: 3 } } })) : Promise.resolve(response({ result: { review_round_id: "rb" } }))); const view = render(ui("a")); await screen.findByText("a"); fireEvent.change(screen.getByLabelText("形成一个由你亲自写下的 claim"), { target: { value: "A" } }); fireEvent.click(screen.getByRole("button", { name: "确认提交检验" })); view.rerender(ui("b")); await screen.findByText("b"); resolveA(response({ result: { claim_id: "ca", aggregate_sequences: { ca: 2 } } })); await Promise.resolve(); const submit = screen.getByRole("button", { name: "确认提交检验" }); expect(submit).toBeEnabled(); fireEvent.change(screen.getByLabelText("形成一个由你亲自写下的 claim"), { target: { value: "B" } }); fireEvent.click(submit); await waitFor(() => expect(fetchMock.mock.calls.some(([u]) => String(u).endsWith("/claims/cb/review-rounds"))).toBe(true)); const claims = fetchMock.mock.calls.filter(([u]) => String(u).endsWith("/claims")); expect(body(claims[1])).toMatchObject({ text: "B", expected_sequence: 0 }); expect(body(claims[1]).command_id).not.toBe(body(claims[0]).command_id) })
  it("late review A cannot clear B flight; B forge navigates its own round", async () => { let resolveA!: (x: Response) => void; fetchMock.mockImplementation((url: string) => url.endsWith("/workspaces/a") ? Promise.resolve(response(desk("a"))) : url.endsWith("/workspaces/b") ? Promise.resolve(response(desk("b"))) : url.endsWith("/claims") ? Promise.resolve(response({ result: { claim_id: url.includes("/b/") ? "cb" : "ca", aggregate_sequences: { cb: 3, ca: 2 } } })) : url.endsWith("/claims/ca/review-rounds") ? new Promise(x => { resolveA = x }) : Promise.resolve(response({ result: { review_round_id: "rb" } }))); const view = render(ui("a")); await screen.findByText("a"); fireEvent.change(screen.getByLabelText("形成一个由你亲自写下的 claim"), { target: { value: "A" } }); fireEvent.click(screen.getByRole("button", { name: "确认提交检验" })); await waitFor(() => expect(fetchMock.mock.calls.some(([u]) => String(u).endsWith("/claims/ca/review-rounds"))).toBe(true)); view.rerender(ui("b")); await screen.findByText("b"); fireEvent.change(screen.getByLabelText("形成一个由你亲自写下的 claim"), { target: { value: "B" } }); fireEvent.click(screen.getByRole("button", { name: "确认提交检验" })); await waitFor(() => expect(fetchMock.mock.calls.some(([u]) => String(u).endsWith("/claims/cb/review-rounds"))).toBe(true)); resolveA(response({ result: { review_round_id: "ra" } })); await Promise.resolve(); expect(window.location.pathname).toBe("/review-rounds/rb"); expect(screen.queryByRole("alert")).not.toBeInTheDocument() })
})
