import { useEffect, useRef, useState, type FormEvent } from "react"
import { command, researchUniverse } from "../api"
import type { CommandEnvelope, WorkspaceDesk as Desk } from "../types"
import { useNavigation } from "../../../router"

type Selection = { start: number; end: number; selected_text: string }
type ClaimIntent = { claim: CommandEnvelope & { text: string }; claimId?: string; review?: CommandEnvelope }
export function WorkspaceDesk({ workspaceId }: { workspaceId: string }) {
  const { navigate } = useNavigation(); const [desk, setDesk] = useState<Desk | null>(null); const [note, setNote] = useState(""); const [selected, setSelected] = useState<Selection>(); const [claim, setClaim] = useState(""); const [error, setError] = useState<string>(); const [conflict, setConflict] = useState(false); const [savePending, setSavePending] = useState(false); const draftGeneration = useRef(0); const noteCommand = useRef<(CommandEnvelope & { text: string }) | undefined>(undefined); const anchorCommand = useRef<(CommandEnvelope & { note_id: string; note_revision_id: string; start: number; end: number; selected_text: string }) | undefined>(undefined); const claimIntent = useRef<ClaimIntent | undefined>(undefined); const claimFlight = useRef<Promise<void> | undefined>(undefined); const routeGeneration = useRef(0); const routeId = useRef(workspaceId); const [claimPending, setClaimPending] = useState(false); const [claimStage, setClaimStage] = useState<"idle" | "saving-claim" | "generating-challenge" | "review-error">("idle");
  async function load(accept = () => true) { try { const value = await researchUniverse.desk(workspaceId); if (accept()) { setDesk(value); if (!noteCommand.current && draftGeneration.current === 0) setNote(value.note?.text ?? ""); setError(undefined) } } catch (e) { if (accept()) setError(e instanceof Error ? e.message : "读取失败") } }
  useEffect(() => { let live = true; routeGeneration.current++; routeId.current = workspaceId; noteCommand.current = undefined; anchorCommand.current = undefined; claimIntent.current = undefined; claimFlight.current = undefined; setSavePending(false); setClaimPending(false); setClaimStage("idle"); setConflict(false); setDesk(null); setError(undefined); setSelected(undefined); draftGeneration.current = 0; void load(() => live); return () => { live = false } }, [workspaceId])
  function editNote(text: string) { draftGeneration.current++; setNote(text); setSelected(undefined); noteCommand.current = undefined }
  const isCurrent = (generation: number, id: string) => generation === routeGeneration.current && id === routeId.current
  async function saveNote() { if (!desk || savePending) return; const currentGeneration = routeGeneration.current, currentId = workspaceId; const generation = draftGeneration.current; noteCommand.current ??= command({ text: note }, desk.sequence); setSavePending(true); try { const result = await researchUniverse.saveNote(currentId, noteCommand.current); if (!isCurrent(currentGeneration, currentId)) return; noteCommand.current = undefined; const fragment = result.fragment as Desk | undefined; if (fragment?.id) { setDesk(fragment); if (draftGeneration.current === generation) { setNote(fragment.note?.text ?? note); draftGeneration.current = 0 } void load(() => isCurrent(currentGeneration, currentId)) } else void load(() => isCurrent(currentGeneration, currentId)) } catch (e) { if (!isCurrent(currentGeneration, currentId)) return; setError(e instanceof Error ? e.message : "保存失败"); if ((e as { status?: number }).status === 409) { noteCommand.current = undefined; setConflict(true); void load(() => isCurrent(currentGeneration, currentId)) } } finally { if (isCurrent(currentGeneration, currentId)) setSavePending(false) } }
  async function anchor() { if (!desk?.note || !selected || note !== desk.note.text || savePending) return; const currentGeneration = routeGeneration.current, currentId = workspaceId; anchorCommand.current ??= command({ note_id: desk.note.note_id ?? desk.note.id, note_revision_id: desk.note.revision_id, ...selected }, desk.sequence); try { await researchUniverse.createAnchor(currentId, anchorCommand.current); if (!isCurrent(currentGeneration, currentId)) return; anchorCommand.current = undefined; void load(() => isCurrent(currentGeneration, currentId)) } catch (e) { if (!isCurrent(currentGeneration, currentId)) return; setError(e instanceof Error ? e.message : "锚点失败"); if ((e as { status?: number }).status === 409) { anchorCommand.current = undefined; setConflict(true); void load(() => isCurrent(currentGeneration, currentId)) } } }
  function forge(e: FormEvent) { e.preventDefault(); if (!desk || !claim.trim() || claimFlight.current) return; const currentGeneration = routeGeneration.current, currentId = workspaceId; claimIntent.current ??= { claim: command({ text: claim.trim() }, 0) }; setClaimPending(true); setClaimStage(claimIntent.current.claimId ? "generating-challenge" : "saving-claim"); claimFlight.current = (async () => { try { if (!claimIntent.current!.claimId) { const made = await researchUniverse.createClaim(currentId, claimIntent.current!.claim); if (!isCurrent(currentGeneration, currentId)) return; claimIntent.current!.claimId = made.result.claim_id; claimIntent.current!.review = command({}, 0); setClaimStage("generating-challenge") } const review = await researchUniverse.startReview(claimIntent.current!.claimId!, claimIntent.current!.review!); if (!isCurrent(currentGeneration, currentId)) return; claimIntent.current = undefined; navigate(`/review-rounds/${review.result.review_round_id}`) } catch (x) { if (!isCurrent(currentGeneration, currentId)) return; setError(claimIntent.current?.claimId ? "主张已保存，但挑战尚未形成。可以重试，不会重复创建主张。" : (x instanceof Error ? x.message : "提交失败")); setClaimStage(claimIntent.current?.claimId ? "review-error" : "idle"); if ((x as { status?: number }).status === 409) { claimIntent.current = undefined; setConflict(true); void load(() => isCurrent(currentGeneration, currentId)) } } finally { if (isCurrent(currentGeneration, currentId)) { claimFlight.current = undefined; setClaimPending(false) } } })() }
  function reapply() { if (!desk) return; setConflict(false); noteCommand.current = undefined; anchorCommand.current = undefined; claimIntent.current = undefined; setError(undefined) }
  if (!desk) return <section className="ru-state" role={error ? "alert" : undefined}>{error ?? "正在展开问题工作区…"}{error && <button className="ru-ink-button" onClick={() => void load()}>重试</button>}</section>
  const pending = desk.pending_challenges[0], anchorReady = Boolean(selected && desk.note && note === desk.note.text && !savePending)
  return <section className="ru-workspace"><header className="ru-question-spine"><p className="ru-kicker">问题工作区 · 探索中</p><h1>{desk.question.text}</h1></header>{error && <p className="ru-error" role="alert">{error}</p>}{conflict && <button className="ru-quiet-button" onClick={reapply}>按最新版本重新应用</button>}<div className="ru-desk-grid"><div className="ru-exploration"><div className="ru-surface-heading"><span>探索稿</span><small>自由记录观察、猜测和未成形判断。Cui 不会在这里回复，也不会自动把内容升格为 Claim 或证据。</small><button className="ru-quiet-button" disabled={savePending} onClick={() => void saveNote()}>保存当前版本</button></div><textarea aria-label="探索稿" className="ru-note" value={note} onChange={(e) => editNote(e.target.value)} onSelect={(e) => { const t = e.currentTarget; const selected_text = t.value.slice(t.selectionStart, t.selectionEnd); setSelected(note === desk.note?.text && selected_text ? { start: t.selectionStart, end: t.selectionEnd, selected_text } : undefined) }} placeholder="写下观察、猜测、反例或尚未成形的判断。" /><button className="ru-quiet-button" disabled={!anchorReady} onClick={() => void anchor()}>保留所选片段</button><form className="ru-claim-form" onSubmit={forge}><label htmlFor="claim">形成一个由你亲自写下的 claim</label><textarea id="claim" value={claim} disabled={claimPending || Boolean(claimIntent.current?.claimId)} onChange={(e) => { setClaim(e.target.value); if (!claimPending) claimIntent.current = undefined }} placeholder="你究竟在断言什么？" required />{claimStage !== "idle" && <p className="ru-claim-progress" aria-live="polite">{claimStage === "saving-claim" ? "正在保存主张…" : claimStage === "generating-challenge" ? "主张已保存，Cui 正在形成挑战…" : "主张已保存，挑战尚未形成。"}</p>}<button className="ru-ink-button" disabled={claimPending}>{claimStage === "review-error" ? "重新形成挑战" : claimStage === "saving-claim" ? "正在保存主张…" : claimStage === "generating-challenge" ? "Cui 正在形成挑战…" : "确认提交检验"}</button></form></div><aside className="ru-research-edge"><p className="ru-kicker">研究边缘</p>{pending ? <a className="ru-pending-fact" href={`/review-rounds/${pending.review_round_id}`}><span>待回应 challenge</span><strong>{pending.id}: {pending.attack_surface}</strong></a> : <p className="ru-edge-empty">尚无待回应事实。</p>}</aside></div></section>
}
