from __future__ import annotations

from datetime import datetime
from uuid import UUID

from anneal.domain.models import (
    Artifact,
    Claim,
    Conversation,
    Library,
    Material,
    Project,
)


def _valid_uuid(s: str) -> bool:
    try:
        UUID(s, version=4)
        return True
    except ValueError:
        return False


# ── Round-trip serialization ──────────────────────────────────────────


class TestLibraryRoundTrip:
    def test_dump_and_validate(self):
        lib = Library(name="my-vault")
        data = lib.model_dump()
        restored = Library.model_validate(data)
        assert restored.name == "my-vault"
        assert restored.id == lib.id
        assert restored.created_at == lib.created_at


class TestProjectRoundTrip:
    def test_dump_and_validate(self):
        proj = Project(library_id="lib-1", goal="build ultrasound probe")
        data = proj.model_dump()
        restored = Project.model_validate(data)
        assert restored.goal == "build ultrasound probe"
        assert restored.library_id == "lib-1"


class TestConversationRoundTrip:
    def test_dump_and_validate(self):
        conv = Conversation(library_id="lib-1", project_ids=["p1", "p2"])
        data = conv.model_dump()
        restored = Conversation.model_validate(data)
        assert restored.project_ids == ["p1", "p2"]
        assert restored.created_at == conv.created_at


class TestClaimRoundTrip:
    def test_dump_and_validate(self):
        claim = Claim(
            library_id="lib-1",
            body="Ultrasound frequency affects resolution",
            artifact_ids=["a1"],
        )
        data = claim.model_dump()
        restored = Claim.model_validate(data)
        assert restored.body == claim.body
        assert restored.artifact_ids == ["a1"]


class TestMaterialRoundTrip:
    def test_dump_and_validate(self):
        mat = Material(
            library_id="lib-1",
            kind="paper",
            provenance={"doi": "10.1234/example"},
            payload={"abstract": "..."},
        )
        data = mat.model_dump()
        restored = Material.model_validate(data)
        assert restored.kind == "paper"
        assert restored.provenance["doi"] == "10.1234/example"


class TestArtifactRoundTrip:
    def test_dump_and_validate(self):
        art = Artifact(
            library_id="lib-1",
            kind="idea",
            goal="prove transducer hypothesis",
            constraints=[{"type": "word_limit", "value": 4000}],
            project_ids=["p1"],
            material_ids=["m1", "m2"],
            title="Transducer hypothesis",
        )
        data = art.model_dump()
        restored = Artifact.model_validate(data)
        assert restored.kind == "idea"
        assert restored.goal == art.goal
        assert restored.constraints == [{"type": "word_limit", "value": 4000}]
        assert restored.project_ids == ["p1"]
        assert restored.material_ids == ["m1", "m2"]
        assert restored.title == "Transducer hypothesis"


# ── Artifact.kind accepts arbitrary strings ───────────────────────────


class TestArtifactKindOpenSet:
    def test_idea(self):
        assert Artifact(library_id="x", kind="idea", goal="g").kind == "idea"

    def test_review(self):
        assert Artifact(library_id="x", kind="review", goal="g").kind == "review"

    def test_paper(self):
        assert Artifact(library_id="x", kind="paper", goal="g").kind == "paper"

    def test_revision(self):
        assert Artifact(library_id="x", kind="revision", goal="g").kind == "revision"

    def test_anything(self):
        assert Artifact(library_id="x", kind="anything", goal="g").kind == "anything"


# ── Material.kind accepts arbitrary strings ───────────────────────────


class TestMaterialKindOpenSet:
    def test_paper(self):
        assert Material(library_id="x", kind="paper").kind == "paper"

    def test_dataset(self):
        assert Material(library_id="x", kind="dataset").kind == "dataset"

    def test_result(self):
        assert Material(library_id="x", kind="result").kind == "result"

    def test_figure(self):
        assert Material(library_id="x", kind="figure").kind == "figure"

    def test_arbitrary(self):
        assert Material(library_id="x", kind="whatever").kind == "whatever"


# ── Claim has NO status field ─────────────────────────────────────────


class TestClaimNoStatus:
    def test_no_status_attribute(self):
        claim = Claim(library_id="x", body="test")
        assert not hasattr(claim, "status") or "status" not in claim.model_fields

    def test_no_status_in_dump(self):
        data = Claim(library_id="x", body="test").model_dump()
        assert "status" not in data


# ── IDs are auto-generated valid UUIDs ────────────────────────────────


class TestAutoGeneratedIds:
    def test_library_id(self):
        assert _valid_uuid(Library(name="x").id)

    def test_project_id(self):
        assert _valid_uuid(Project(library_id="x", goal="g").id)

    def test_conversation_id(self):
        assert _valid_uuid(Conversation(library_id="x").id)

    def test_claim_id(self):
        assert _valid_uuid(Claim(library_id="x", body="b").id)

    def test_material_id(self):
        assert _valid_uuid(Material(library_id="x", kind="paper").id)

    def test_artifact_id(self):
        assert _valid_uuid(Artifact(library_id="x", kind="idea", goal="g").id)

    def test_ids_are_unique(self):
        ids = [Library(name="x").id for _ in range(100)]
        assert len(set(ids)) == 100


# ── Datetimes are auto-populated ──────────────────────────────────────


class TestAutoDatetimes:
    def test_library_created_at(self):
        lib = Library(name="x")
        assert isinstance(lib.created_at, datetime)

    def test_conversation_timestamps(self):
        conv = Conversation(library_id="x")
        assert isinstance(conv.created_at, datetime)
        assert isinstance(conv.updated_at, datetime)

    def test_claim_timestamps(self):
        claim = Claim(library_id="x", body="b")
        assert isinstance(claim.created_at, datetime)
        assert isinstance(claim.updated_at, datetime)

    def test_artifact_timestamps(self):
        art = Artifact(library_id="x", kind="idea", goal="g")
        assert isinstance(art.created_at, datetime)
        assert isinstance(art.updated_at, datetime)
